### ISSUE TITLE
How do you get the URL to the specific video?

### ISSUE THREAD

**Issue by RemoPro** [mikeswanson/WallGet#1]
Cool project. I wonder how you get the URL to each specific video. I founded out that the URLs are in a json file but when I opened these in Safari it only shows an error.

![image](https://github.com/mikeswanson/WallGet/assets/55060292/ffeb03da-6d10-4468-9a32-fe3181eb1c44)

**Comment by mikeswanson** [comment]
The URL is read from the **entries.json** file in Sonoma. You can see where it's read here: https://github.com/mikeswanson/WallGet/blob/6b342704b39c35836148519cbc5cc3a43fd3feb5/wallget.py#L85

Looks like a similar file to what you've shown. Note that those URLs need to be unescaped. In this case, every instance of "\\/" needs to be replaced by a single "/".

I see that your **entries-large.json** file has additional video sizes/rates. Where did you get this file? I've looked for an example with other sizes/rates with no luck. My Sonoma installation only includes **url-4K-SDR-240FPS** entries.

**Comment by dmn001** [comment]
Path to the entries-large.json file: https://gist.github.com/theothernt/57a51cade0c12c407f48a5121e0939d5?permalink_comment_id=4598333#gistcomment-4598333

**Comment by RemoPro** [comment]
> The URL is read from the **entries.json** file in Sonoma. You can see where it's read here: https://github.com/mikeswanson/WallGet/blob/6b342704b39c35836148519cbc5cc3a43fd3feb5/wallget.py#L85
> 
> 
> 
> Looks like a similar file to what you've shown. Note that those URLs need to be unescaped. In this case, every instance of "\\/" needs to be replaced by a single "/".
> 
> 
> 
> I see that your **entries-large.json** file has additional video sizes/rates. Where did you get this file? I've looked for an example with other sizes/rates with no luck. My Sonoma installation only includes **url-4K-SDR-240FPS** entries.

I found the file in macOS 14 Beta on 9/28/2023 there:

/System/Library/PrivateFrameworks/TVIdleServices.framework/Versions/A/Resources/entries-large.json
