### ISSUE TITLE
57GB of wallpapers on Sequoia

### ISSUE THREAD

**Issue by albinkc** [mikeswanson/WallGet#2]
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/dfd59a2f-131e-4a07-84ae-5759d776759a">

Just wanted to make sure if this is the expected size for downloading all wallpapers and not a bug. That size seems enormous

**Comment by mikeswanson** [comment]
Indeed...it actually looks smaller than when I originally wrote the README.md which says ~65GB. They've probably recompressed them. They're 240fps video files in very high quality, so yes, they're huge.

**Comment by albinkc** [comment]
Thanks for the clarification. Regarding the smaller size, I did download some by clicking manually before finding your project, so that might be it.
